### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Alexromer2** [rstudio/tensorflow#582] opened 2023-09-17 18:23 UTC
I've been trying to get tensorflow and keras to work in Rstudio on my system for the past several days but despite my best efforts I haven't been able to do so. I have been able to download the packages, create virtual enviroments, install packages into them via the windows command line, but still have not been able to get models to run successfully. Any assistance would be greatly appreciated. 

Please provide the output of demo code for tensorflow from rstudio as well as the suggested diagnosistic outputs. 

<html>
<body>
<pre tabindex="0" aria-label="Console Output" role="document" class="GND-IWGDH3B" id="rstudio_console_output" style="font-family: &quot;Lucida Console&quot;, monospace; font-size: 13.3333px; outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; line-height: 1.2; color: rgb(234, 234, 234); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: -webkit-left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(44, 40, 40); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">library(reticulate)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">library(tensorflow)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">library(keras)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">library(tidyverse)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">c(c(x_train, y_train), c(x_test, y_test)) %&lt;-% keras::dataset_mnist()
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">x_train &lt;- x_train / 255
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">x_test &lt;-  x_test / 255
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">model &lt;- keras_model_sequential(input_shape = c(28, 28)) %&gt;%
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  layer_flatten() %&gt;%
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  layer_dense(128, activation = "relu") %&gt;%
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  layer_dropout(0.2) %&gt;%
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  layer_dense(10)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">predictions &lt;- predict(model, x_train[1:2, , ])
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">1/1 [==============================] - 0s 47ms/step
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">predictions
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">            [,1]      [,2]       [,3]        [,4]      [,5]       [,6]      [,7]      [,8]       [,9]      [,10]
[1,]  0.01118694 0.2813529 0.57456416  0.08346558 0.3401761 -0.7518407 0.6589657 0.1194443 -0.4665765  0.1722614
[2,] -0.25449932 0.6129925 0.05429347 -0.41096535 0.8672591 -1.1021731 0.9212947 0.1462670 -0.1371493 -0.3343928
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">tf$nn$softmax(predictions)
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">tf.Tensor(
[[0.08461587 0.11086219 0.14863581 0.09095824 0.11757907 0.03945237
  0.16172553 0.09429039 0.05247613 0.0994044 ]
 [0.06298045 0.14995215 0.08576553 0.0538584  0.19336563 0.02698148
  0.20410172 0.09402782 0.07082233 0.05814448]], shape=(2, 10), dtype=float64)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">loss_fn &lt;- loss_sparse_categorical_crossentropy(from_logits = TRUE)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">loss_fn(y_train[1:2], predictions)
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">tf.Tensor(2.998795959859347, shape=(), dtype=float64)
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">model %&gt;% compile(
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  optimizer = "adam",
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  loss = loss_fn,
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">  metrics = "accuracy"
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">+ </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">)
</span><div class="GND-IWGDPHD ace_console_error" style="position: relative; overflow: hidden; margin: 5px 5px 5px 0px; padding: 5px 0px 5px 10px; white-space: pre-line; background-color: rgb(82, 78, 78);"><div class="GND-IWGDAID" style="top: 5px; float: right; margin-right: 10px; margin-left: 5px; margin-bottom: 15px; line-height: 10.6667px; position: relative; user-select: none;"><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAaElEQVR42mNgwAXWv8sEY4rA2vd+DOve/wFjEJsssOGjOdCA/ygYJEYS2PhRBcMQGAbJEQVWfRbFaQgMg9TgBZufcRE0BIZBarG75D8z0YbAXQbUgwFINQSGCQKyNY4aRLoFw9iggQYAE6xnKErSS9EAAAAASUVORK5CYII=" width="18" height="18" class="GND-IWGDBID show_traceback_image" alt="" aria-hidden="true" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GND-IWGDCID show_traceback_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Show Traceback</a></div><div><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABU0lEQVR42pWUP0vEMBjGo4uz2rQO4iS66KCC4OSoi99C/ATu9zn8AKII16QOgoLgoCD+WR28tUnuThQUp0OvPm+8P9ZrSxJ4hjZ9fn2TPG8YKxlT9XQ2FPqAC6O40B3oKojNJvMZ08Ksw/gGZf/0FUi16wSZPFVzMLQLIH11wjjdGDEGdbXKatn44FloUQHp634AgNcy8PKCS30dyeYyT9SKA8SKlh/FzSXyEoOxLBtDFXu95dy5ggKhbslD3r8rYmHSijDx7gqyPz5pz4zuMqh0Kh6gl5zfw1ipXAA9zd+F+Zk/a0xgsusKQupfS8OIdmh4VPRYCPk9NS/QM3mGhGGOWij30B1kjsljcwQGndo5dEPJtpUJdekAeqK42G6A1yYbxLVcr8XpAiY+KyDdUOqtXK8Ro3DTY71dAgPE7HvdSUGiFrk0RzB/9BL/gLtop+z7HzowRJ/sYbqcAAAAAElFTkSuQmCC" width="18" height="18" class="GND-IWGDBID rerun_image" alt="" style="cursor: pointer; width: 9px !important; height: 9px !important;"> <a class="GND-IWGDCID rerun_text" style="font-family: &quot;Segoe UI&quot;, serif; font-size: 10.6667px; opacity: 0.5; cursor: pointer;">Rerun with Debug</a></div></div><div class="GND-IWGDDID GND-IWGDB3B  ace_constant ace_language" style="display: inline; overflow-wrap: break-word; word-break: break-word; color: rgb(222, 142, 48);"><span>Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
TypeError: __init__() missing 1 required positional argument: 'args'
</span><span class="xtermColor8" style="color: rgb(124, 124, 124) !important;">Run </span><a class="GND-IWGDOJ xtermColor8" style="text-decoration: underline dotted; cursor: pointer; color: rgb(124, 124, 124) !important;">`reticulate::py_last_error()`</a><span class="xtermColor8" style="color: rgb(124, 124, 124) !important;"> for details.</span></div><div class="GND-IWGDEID stack_trace" aria-hidden="true" style="margin-top: 0.5em; margin-left: 0.3em; display: block;">

6. | stop(<environment>)
-- | --

</div></div><span>
</span></span><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);"># If the above installation failed, please gather some diagnostic info
</span><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">reticulate::py_config()
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">python:         C:/Users/alexr/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe
libpython:      C:/Users/alexr/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll
pythonhome:     C:/Users/alexr/Documents/.virtualenvs/r-tensorflow
version:        3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/alexr/Documents/.virtualenvs/r-tensorflow/Lib/site-packages/numpy
numpy_version:  1.24.3
tensorflow:     C:\Users\alexr\DOCUME~1\VIRTUA~1\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by import("tensorflow")
</span></span><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">tensorflow::tf_config()
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">TensorFlow v2.13.0 (C:\Users\alexr\DOCUME~1\VIRTUA~1\R-TENS~1\lib\site-packages\tensorflow\__init__.p)
Python v3.9 (~/.virtualenvs/r-tensorflow/Scripts/python.exe)
</span></span><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">reticulate::py_last_error()
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
</span><span class="GND-IWGDH3B xtermColor6" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(198, 197, 254) !important;">──</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"> </span><span class="GND-IWGDH3B xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold;">Python Exception Message</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"> </span><span class="GND-IWGDH3B xtermColor6" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(198, 197, 254) !important;">────────────────────────────────────────────────────────────────────────────────────────────────────────</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
TypeError: 'SparseCategoricalCrossentropy' object is not subscriptable

</span><span class="GND-IWGDH3B xtermColor6" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(198, 197, 254) !important;">──</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"> </span><span class="GND-IWGDH3B xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold;">R Traceback</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;"> </span><span class="GND-IWGDH3B xtermColor6" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(198, 197, 254) !important;">─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">     </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">▆
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  1. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">└─.rs.environment.isSuspendable()
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  2. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">  ├─</span><span class="GND-IWGDH3B xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold;">base</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">::tryCatch(...)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  3. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">  │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  4. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">  │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  5. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">  │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  6. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">  └─.rs.environment.isSuspendableImpl(globalenv(), 1L)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  7. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">    └─.rs.environment.isSuspendableImpl(value[[key]], depth + 1L)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  8. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">      ├─.rs.environment.isSuspendableImpl(value[[i]], depth + 1L)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;">  9. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">      ├─value[[i]]
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;"> 10. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">      └─</span><span class="GND-IWGDH3B xtermBold" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; font-weight: bold;">reticulate</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">:::`[[.python.builtin.object`(value, i)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;"> 11. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">        └─reticulate:::py_get_attr_or_item(x, name, FALSE)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;"> 12. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">          └─reticulate::py_get_item(x, name)
</span><span class="GND-IWGDH3B xtermColor8" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important; color: rgb(124, 124, 124) !important;"> 13. </span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">            └─reticulate:::py_get_item_impl(x, key, silent)
</span></span><span tabindex="-1" class="GND-IWGDI3B" role="document" style="outline: none;"><span class="GND-IWGDO3B ace_keyword" style="color: rgb(117, 122, 216); white-space: pre; user-select: text;">&gt; </span><span class="GND-IWGDN2B ace_keyword" style="color: rgb(117, 122, 216);">sessionInfo()
</span><span class="GND-IWGDH3B" style="outline: none; border: none; word-break: break-all; margin: 0px; user-select: text; white-space: pre-wrap !important;">R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.2        forcats_1.0.0          stringr_1.5.0          dplyr_1.1.2            purrr_1.0.1           
 [6] readr_2.1.4            tidyr_1.3.0            tibble_3.2.1           ggplot2_3.4.2          tidyverse_2.0.0       
[11] keras_2.13.0.9000      tensorflow_2.13.0.9000 reticulate_1.32.0.9000

loaded via a namespace (and not attached):
 [1] Matrix_1.5-4      gtable_0.3.3      jsonlite_1.8.7    compiler_4.3.0    tidyselect_1.2.0  Rcpp_1.0.11       zeallot_0.1.0    
 [8] tfruns_1.5.1      scales_1.2.1      png_0.1-8         lattice_0.21-8    here_1.0.1        R6_2.5.1          generics_0.1.3   
[15] munsell_0.5.0     rprojroot_2.0.3   tzdb_0.3.0        pillar_1.9.0      rlang_1.1.1       utf8_1.2.3        stringi_1.7.12   
[22] timechange_0.2.0  cli_3.6.1         withr_2.5.0       magrittr_2.0.3    grid_4.3.0        rstudioapi_0.15.0 hms_1.1.3        
[29] remotes_2.4.2.1   base64enc_0.1-3   lifecycle_1.0.3   vctrs_0.6.3       glue_1.6.2        whisker_0.4.1     fansi_1.0.4      
[36] colorspace_2.1-0  tools_4.3.0       pkgconfig_2.0.3  </span></span></pre>
</body>
</html>`

**Comment by t-kalinowski** [comment] 2023-09-18 12:49
Thank you for the bug report, I could reproduce. This was a bug in the development version of reticulate, which should be now fixed. Can you please install the latest development version and see if the issue is fixed?
```r
pak::pak("rstudio/reticulate", ask = FALSE)
```

**Comment by Alexromer2** [comment] 2023-09-18 17:12
Thank you for such a prompt reply!

> Thank you for the bug report, I could reproduce. This was a bug in the development version of reticulate, which should be now fixed. Can you please install the latest development version and try again?
> 
> ```r
> pak::pak("rstudio/reticulate", ask = FALSE)
> ```

I tried installing you using the `pak` package but got the following error 

```
> pak::pak("rstudio/reticulate", ask = FALSE)
Error in load_private_package("glue") : 
  Cannot load glue from the private library
```

**Comment by t-kalinowski** [comment] 2023-09-18 17:27
Installation of R packages can fail on Windows if the package is already loaded. This is especially tricky for packages like reticulate, or glue, since the package namespace might be loaded by the IDE.

Make sure you've quit any other sessions of Rstudio / R, and try to again. You can also try using `remotes::install_github("rstudio/reticulate")`, if this is a {pak} specific bug.

**Comment by Alexromer2** [comment] 2023-09-18 18:05
That did the trick!
```
> model %>% compile(
+   optimizer = "adam",
+   loss = loss_fn,
+   metrics = "accuracy"
+ )
> 
> model %>% fit(x_train, y_train, epochs = 5)
Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0660 - accuracy: 0.9792
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0602 - accuracy: 0.9798
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0535 - accuracy: 0.9826
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0484 - accuracy: 0.9842
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0442 - accuracy: 0.9852 
```
Diagnositic info for future reference 
```
> reticulate::py_config()
python:         C:/Users/alexr/Documents/.virtualenvs/r-tensorflow/Scripts/python.exe
libpython:      C:/Users/alexr/AppData/Local/r-reticulate/r-reticulate/pyenv/pyenv-win/versions/3.9.13/python39.dll
pythonhome:     C:/Users/alexr/Documents/.virtualenvs/r-tensorflow
version:        3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/alexr/Documents/.virtualenvs/r-tensorflow/Lib/site-packages/numpy
numpy_version:  1.24.3
tensorflow:     C:\Users\alexr\DOCUME~1\VIRTUA~1\R-TENS~1\lib\site-packages\tensorflow\__init__.p

NOTE: Python version was forced by import("tensorflow")
> tensorflow::tf_config()
TensorFlow v2.13.0 (C:\Users\alexr\DOCUME~1\VIRTUA~1\R-TENS~1\lib\site-packages\tensorflow\__init__.p)
Python v3.9 (~/.virtualenvs/r-tensorflow/Scripts/python.exe)
```

Thank you greatly!

**Closed** 2023-09-29 14:47 UTC
