### ISSUE TITLE
Any reliable install routine on a fresh system (GPU)?

### ISSUE THREAD

**Issue by AgatheBauer** [rstudio/tensorflow#330] opened 2019-06-07 18:28 UTC
I'm reading a lot about installation problems here. I succeeded with the official install routine in summer 2018, however since I reset my system and installed a clean Windows 10 64bit Version 10.0.18362.145, I got only troubles.

This was the install routine I was following (GPU version):

Install...

Windows 10 Version 10.0.18362.145 64bit (clean install)
R-3.6.0
R-Studio 1.2.1335
Rtools35
Nvidia Display Driver 26.21.14.3086 (GTX 1060 3GB)
cuda_9.0.176_win10 -> update to 9.0.176.1 -> 9.0.176.2 -> 9.0.176.3 (
cudnn-9.0-windows10-x64-v7.1.zip  -> unzip cudnn64_7.dll to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin

Anaconda3-2019.03-Windows-x86_64 (don't register PATH) -> downgrade to Anaconda3-5.2.0-Windows-x86_64 after error messages that I can't recall.

in R-Studio:
```
install.packages('devtools')
devtools::install_github("rstudio/tensorflow") 
devtools::install_github("rstudio/keras") 
```

So far no problems (other than I had to downgrade Anaconda).

However when I'm trying to construct a model with 

`keras_model_sequential()`

I'm getting this:

> Error: Python module tensorflow.python.keras was not found.
> 
> Detected Python configuration:
> 
> python:         C:\Users\simeo\Anaconda3\envs\r-tensorflow\python.exe
> libpython:      C:/Users/simeo/Anaconda3/envs/r-tensorflow/python37.dll
> pythonhome:     C:\Users\simeo\ANACON~1\envs\R-TENS~1
> version:        3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:\Users\simeo\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
> numpy_version:  1.16.3
> tensorflow:     C:\Users\simeo\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p
> 
> python versions found: 
>  C:\Users\simeo\Anaconda3\envs\r-tensorflow\python.exe
>  C:\Users\simeo\AppData\Local\MICROS~1\WINDOW~1\python.exe
>  C:\Users\simeo\ANACON~1\python.exe
>  C:\Users\simeo\Anaconda3\python.exe
> 

What did I do wrong?

**Comment by AgatheBauer** [comment] 2019-06-08 18:11
https://github.com/rstudio/tensorflow/issues/311

This worked.

**Comment by AgatheBauer** [comment] 2019-06-09 18:48
But only temporarily. I really don't know what broke it again.

When I'm trying to train my neural net like this:

```
model %>% fit(
    X_train, Y_train, 
    epochs = 100, batch_size = 1000, 
    validation_split = 0.25, shuffle = FALSE
```

...with a really small neural net and a really small dataset (just a little over 20 MB), so memory shouldn't be a problem...

I'm getting this:

> 2019-06-09 20:37:13.411281: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
> 2019-06-09 20:37:13.783395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
> name: GeForce GTX 1060 3GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
> pciBusID: 0000:01:00.0
> totalMemory: 3.00GiB freeMemory: 2.43GiB
> 2019-06-09 20:37:13.784168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
> 2019-06-09 20:37:15.846785: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-06-09 20:37:15.847073: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
> 2019-06-09 20:37:15.847237: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
> 2019-06-09 20:37:15.850517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2116 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2019-06-09 20:37:16.516460: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_100.dll locally
> 2019-06-09 20:37:17.155690: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.157526: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.158056: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.158461: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.172835: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.173674: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.174455: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.174775: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.175186: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.175499: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.176144: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.182172: E tensorflow/stream_executor/cuda/cuda_blas.cc:510] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
> 2019-06-09 20:37:17.182668: W tensorflow/stream_executor/stream.cc:2130] attempting to perform BLAS operation using StreamExecutor without BLAS support
>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   InternalError: Blas GEMM launch failed : a.shape=(1000, 129), b.shape=(129, 20), m=1000, n=20, k=129

Can I somehow avoid all this hassle by installing an older version?

**Comment by dfalbel** [comment] 2019-06-10 01:56
This error is related to the GPU memory. You probably have another session running tensorflow and it allocates all GPU memory. 

Try closing all Rstudio sessions and re-running your code.

**Comment by AgatheBauer** [comment] 2019-06-10 05:02
I rebooted my system and also tried `.rs.restartR()`. The error persists.

**Comment by dfalbel** [comment] 2019-06-10 10:59
Can you try fitting with a smaller batch size? I still that the problem is that your GPU doesn't have enough memory.

**Comment by AgatheBauer** [comment] 2019-06-10 15:50
Reduced to 100, didn't help. The main reason I'm sure it's not a memory issue is, that it was working before I reinstalled my system.

**Comment by dfalbel** [comment] 2019-06-11 10:40
What do you have in `nvidia-smi` just before running `fit`? Each session of TensorFlow allocates all available GPU memory by default, so if you have two R sessions running Tensorflow, that could be the issue.

Can you share what's your `tf_config()`?

**Closed** 2019-07-01 06:32 UTC

**Comment by tsengj** [comment] 2019-10-31 05:08
What was the resolution to this issue? I experienced the same. Installed successfully, ran a few successful runs. And now encountered this issue repeatedly even after i restarted windows.

```
network %>% fit(train_images, train_labels, epochs = 5, batch_size = 128)
2019-10-31 16:02:45.104660: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-10-31 16:02:45.353681: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.354245: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.355386: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.355668: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.355944: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.357659: E tensorflow/stream_executor/cuda/cuda_blas.cc:238] failed to create cublas handle: CUBLAS_STATUS_ALLOC_FAILED
2019-10-31 16:02:45.357876: W tensorflow/stream_executor/stream.cc:1919] attempting to perform BLAS operation using StreamExecutor without BLAS support
2019-10-31 16:02:45.358072: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Internal: Blas GEMM launch failed : a.shape=(128, 784), b.shape=(784, 512), m=128, n=512, k=784
	 [[{{node sequential/dense/MatMul}}]]
Train on 60000 samples
Epoch 1/5
  128/60000 [..............................] - ETA: 9:06Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError:  Blas GEMM launch failed : a.shape=(128, 784), b.shape=(784, 512), m=128, n=512, k=784
	 [[node sequential/dense/MatMul (defined at \framework\ops.py:1751) ]] [Op:__inference_distributed_function_712]

Function call stack:
distributed_function
```

**Comment by tsengj** [comment] 2019-11-01 04:15
@AgatheBauer Thanks. I got mine working after reinstalling it. with the following command line

`devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
tensorflow::install_tensorflow(method = "auto",version = "gpu")

`devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
tensorflow::install_tensorflow(method = "auto",version = "gpu")

library(keras)
install_keras(method = 'auto',
              conda = "auto", version = "default", tensorflow = "gpu")`
