### ISSUE TITLE
[Example does not run] Unable to convert R object to Python type

### ISSUE THREAD

**Issue by jintaili** [rstudio/tensorflow#384] opened 2019-12-11 23:02 UTC
Hi! I am trying to write feedforward networks in the sequential API, but cannot reproduce the example [here](https://tensorflow.rstudio.com/tutorials/advanced/). Specifically, when converting the dataset using the following lines:
```
train_ds <- mnist$train %>% 
  tensor_slices_dataset() %>%
  dataset_take(20000) %>% 
  dataset_map(~modify_at(.x, "x", tf$cast, dtype = tf$float32)) %>% 
  dataset_map(~modify_at(.x, "y", tf$cast, dtype = tf$int64)) %>% 
  dataset_shuffle(10000) %>% 
  dataset_batch(32)
```
R prompts the following error message:
```
Error in py_call_impl(callable, dots$args, dots$keywords) :
  Evaluation error: Unable to convert R object to Python type.
```
It seems still possible to run the example by taking out the `cast()` lines, because tf automatically coerces them into the proper format. However, I cannot achieve that with my own feedforward neural network. In short, I want to understand the format and dimension of data needed to run the sequential API and how to get them. Thanks!

**Comment by dfalbel** [comment] 2019-12-11 23:05
Can you try installing the dev version of `tfdatasets`. Running:

```
remotes::install_github("rstudio/tfdatasets")
```

Also, what's your `tensorflow::tf_version()`?

**Comment by jintaili** [comment] 2019-12-11 23:18
Hi @dfalbel ! My tf version is 2.0. I tried the dev version just now, selecting 'None' when prompted what packages I wanted to update. But the same issue persists.

As a supplement, I tried to run my dataset, which is of type 'double' without the `cast()`. I get the following error when estimating:
```
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: 'NoneType' object is not callable
```

**Comment by jintaili** [comment] 2019-12-12 17:44
Update: The error message now changed for unknown reasons. Coming back to the MNIST example, when I run `mnist$train %>% tensor_slices_dataset()` for the first time in R session, the following warning message comes up:
```
2019-12-12 12:35:32.387645: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-12 12:35:32.398099: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fdb7d501140 executing computations on platform Host. Devices:
2019-12-12 12:35:32.398115: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
```
This does not interrupt the procedure, but when I proceed to run `mnist$train %>% tensor_slices_dataset() %>% dataset_take(20000) %>% dataset_map(~modify_at(.x, "x", tf$cast, dtype = tf$float32))`, the following error comes up:
```
 *** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
 1: py_call_impl(callable, dots$args, dots$keywords)
 2: dataset$map(map_func = as_py_function(map_func), num_parallel_calls = as_integer_tensor(num_parallel_calls,     tf$int32))
 3: is_dataset(dataset)
 4: as_tf_dataset(dataset$map(map_func = as_py_function(map_func),     num_parallel_calls = as_integer_tensor(num_parallel_calls,         tf$int32)))
 5: dataset_map(., ~modify_at(.x, "x", tf$cast, dtype = tf$float32))
 6: function_list[[k]](value)
 7: withVisible(function_list[[k]](value))
 8: freduce(value, `_function_list`)
 9: `_fseq`(`_lhs`)
10: eval(quote(`_fseq`(`_lhs`)), env, env)
11: eval(quote(`_fseq`(`_lhs`)), env, env)
12: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
13: mnist$train %>% tensor_slices_dataset() %>% dataset_take(20000) %>%     dataset_map(~modify_at(.x, "x", tf$cast, dtype = tf$float32))

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```
Interestingly, I can ignore this message by pressing ctrl+c, and run the code again to coerce my `train_ds` into format:
```
<BatchDataset shapes: {x: (None, 28, 28, 1), y: (None,)}, types: {x: tf.float32, y: tf.int64}>
```
But when I proceed to execute `training_loop()`, the epochs finish instantaneously, and `model` remains `Custom Keras model: not yet fitted`.

sessionInfo:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] graphics  grDevices datasets  stats     utils     methods   base

other attached packages:
 [1] purrr_0.3.3                     reticulate_1.13                 tfautograph_0.1.0               tfdatasets_1.13.1.9000          tensorflow_2.0.0
 [6] keras_2.2.5.0                   dtplyr_0.0.3                    rsutils_6.07.00010110248        rsugeneral_6.07.000485049       rsuxls_6.07.000495052
[11] rsuworkspace_6.07.000539753     rsuvydia_6.07.000995099         rsushiny_6.07.00010110057       rsuscrubbers_1.09.003545398     rsuprophesize_1.09.003545052
[16] rsuplotting_6.07.0001029751     rsunotify_6.07.000575751        rsujesus_6.07.0005551101        rsuaws_6.07.000985053           rsudb_6.07.000495050
[21] rsucurl_1.09.003535750          rsuconsoleutils_6.07.0005110250 rsubitly_1.09.0035650101        rsuaspath_6.07.000564951        rcreds_0.7.7
[26] collectArgs_0.5.0               magrittr_1.5                    dplyr_0.8.3                     data.table_1.12.2               colorout_1.2-2
```

Thank you!

**Comment by dfalbel** [comment] 2019-12-16 14:52
I'm sorry, but I still can't reproduce you error. What happens when you run:

```
library(keras)
library(purrr)
library(tfdatasets)

mnist <- dataset_mnist()

train_ds <- mnist$train %>% 
  tensor_slices_dataset() %>%
  dataset_take(20000) %>% 
  dataset_map(~modify_at(.x, "x", tf$cast, dtype = tf$float32)) %>% 
  dataset_map(~modify_at(.x, "y", tf$cast, dtype = tf$int64)) %>% 
  dataset_shuffle(10000) %>% 
  dataset_batch(32)
```

**Comment by jintaili** [comment] 2019-12-16 22:09
Hi @dfalbel - yes! If I run those lines for the first time in an R session, this pops up:
```
2019-12-16 17:03:39.043607: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-12-16 17:03:39.063850: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe49cc57820 executing computations on platform Host. Devices:
2019-12-16 17:03:39.063876: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version

 *** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
 1: py_call_impl(callable, dots$args, dots$keywords)
 2: dataset$map(map_func = as_py_function(map_func), num_parallel_calls = as_integer_tensor(num_parallel_calls,     tf$int32))
 3: is_dataset(dataset)
 4: as_tf_dataset(dataset$map(map_func = as_py_function(map_func),     num_parallel_calls = as_integer_tensor(num_parallel_calls,         tf$int32)))
 5: dataset_map(., ~modify_at(.x, "x", tf$cast, dtype = tf$float32))
 6: function_list[[i]](value)
 7: freduce(value, `_function_list`)
 8: `_fseq`(`_lhs`)
 9: eval(quote(`_fseq`(`_lhs`)), env, env)
10: eval(quote(`_fseq`(`_lhs`)), env, env)
11: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
12: mnist$train %>% tensor_slices_dataset() %>% dataset_take(20000) %>%     dataset_map(~modify_at(.x, "x", tf$cast, dtype = tf$float32)) %>%     dataset_map(~modify_at(.x, "y", tf$cast, dtype = tf$int64)) %>%     dataset_shuffle(10000) %>% dataset_batch(32)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:
```
I could ctrl+c out of this situation and seemingly successfully batch my dataset, but still cannot estimate the model.

I actually have a more detailed breakdown of the situation in a [previous comment](https://github.com/rstudio/tensorflow/issues/384#issuecomment-565111040).

**Comment by skeydan** [comment] 2019-12-17 07:57
Could you indicate the output of

```
packageVersion("rlang")
rlang::as_function(~modify_at(.x, "x", tf$cast, dtype = tf$float32))
reticulate::r_to_py(rlang::as_function(~modify_at(.x, "x", tf$cast, dtype = tf$float32)))
```

?

**Comment by jintaili** [comment] 2019-12-17 20:15
Hi @skeydan - Yes they are as follows:
```
> packageVersion("rlang")
[1] ‘0.4.0’
> rlang::as_function(~modify_at(.x, "x", tf$cast, dtype = tf$float32))
<lambda>
    [ ARG ] ................. [ VALUE ]
    ... .............................
    .x ............................ ..1
    .y ............................ ..2
    . ............................. ..1
            // in GlobalEnv //
> reticulate::r_to_py(rlang::as_function(~modify_at(.x, "x", tf$cast, dtype = tf$float32)))
<function python_function at 0x10e8dbde8>
```

**Comment by t-kalinowski** [comment] 2021-06-04 17:54
Hi, we can't reproduce the issue. I'm closing this for now. If you're still encountering this problem with the latest versions of the R packages tensorflow, keras, tfdatasets, reticulate, and rlang, please reopen the issue.

**Closed by t-kalinowski** 2021-06-04 17:54 UTC
Labels: analysis
